INSERT INTO `academigymraeg`.`noun_request` VALUES
(1,"Colour", "colour / color", "MALE", "Lliw"),
(2,"Bread", "", "MALE", "Bara"),
(3,"Milk","","MALE","Llaeth"),
(4,"Butter","Can also be ymenyn","MALE","menyn"),
(5,"Cheese","","MALE","Caws"),
(6,"Dinner","","MALE","Cinioa"),
(7,"Town","","FEMALE","Tref"),
(8,"Village","Can also be pentref","MALE","Pentre"),
(9,"Chair","","FEMALE","Cadair"),
(10,"Boy","Can also be hogyn or llanc","MALE","Bachgen"),
(11,"Girl","Can also be geneth or hogan","FEMALE","Merch"),
(12,"Hand","","FEMALE","Llaw"),
(13,"Arm","","FEMALE","Braich"),
(14,"Cheeks","","FEMALE","Gruddiau"),
(15,"Chest","","FEMALE","brest"),
(16,"Chin","Should be Gên","FEMALE","Gen"), 
(17,"Ear","","FEMALE","Clust"),
(18,"Head","","MALE","Pen"),
(19,"Shoulders","","MALE","Ysgwyddau"),
(20,"Knees","Coesau means legs, but commonly used in replacement for knees","MALE","Gliniau"),
(21,"Elbow","Can be either masc or fem, most commonly masc","MALE","Penelin"),
(22,"Feet","","MALE","Traed"),
(23,"Cat","","FEMALE","Cath"),
(24,"Dog","","MALE","Ci"),
(25,"Parrot","","MALE","Parot"),
(26,"Fish","","MALE","Pysgodyn"),
(27,"Sheep","Singular","FEMALE","Dafad"),
(28,"Cow","","FEMALE","Buwch"),
(29,"Pig","","MALE","Mochyn"),
(30,"Rabbit","","FEMALE","Cwningen"),
(31,"Duck","","FEMALE","Hwyaden"),
(32,"Horse","","MALE","Ceffyl"),
(33,"Coat","Côt","FEMALE","Cot"),
(34,"T Shirt","","MALE","Crys T"),
(35,"Shoes","","FEMALE","Esgidiau"),
(36,"School Uniform","","FEMALE","Gwisg Ysgol"),
(37,"Hat","","FEMALE","Het"),
(38,"Socks","","FEMALE","Sanau"),
(39,"Jeans","","MALE","jîns"),
(40,"Gloves","","FEMALE","Menig"),
(41,"Scarf","","FEMALE","Sgarff"),
(42,"Skirt","","FEMALE","Sgert"),
(43,"Jumper","","FEMALE","Siwmpier"),
(44,"Tie","","MALE","Tei"),
(45,"Trousers","","MALE","Trowser");